language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly
matrix:
  allow_failures:
    - php: 7
    - php: nightly

env:
  matrix:
    - MAGENTO_VERSION="magento-ce-1.9.2.2"
    - MAGENTO_VERSION="magento-ce-1.9.0.1"
    - MAGENTO_VERSION="magento-ce-1.8.1.0"
    - MAGENTO_VERSION="magento-ce-1.8.0.0"
    - MAGENTO_VERSION="magento-ce-1.7.0.2"
    - MAGENTO_VERSION="magento-ce-1.6.2.0"
    - MAGENTO_VERSION="magento-mirror-1.5.1.0"
    - MAGENTO_VERSION="magento-mirror-1.4.2.0"
  global:
    - secure: "....."
script: bin/phpunit

after_script:
  - if [[ $TRACE_CODE_COVERAGE=1 ]]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

